### ISSUE TITLE
Cells are not being dequeued

### ISSUE THREAD

**Issue by jordanhbuiltbyhq** [danielamitay/DAAutoScroll#3]
The table view cells are not being dequeued while auto scrolling for some reason. Crazily, once you manually scroll they are reused, then after a bit more autoscrolling they'll stop being dequeuing again. You can return 1000 cells and watch the memory usage and CPU usage gradually increase as it auto scrolls. Eventually, this causes SpringBoard to crash or completely restart the phone.

**Comment by jordanhbuiltbyhq** [comment]
This is caused by wrapping `self.contentOffset = newOffset;` inside the UIView animation block. Taking it out of there resolves the issue.

**Comment by danielamitay** [comment]
Hey there @jordanhbuiltbyhq! I think I haven't touched DAAutoScroll in 4 years, but give me a few days and I think I can re-do this with `CADisplayLink` instead of `NSTimer` + animation, which should work the same and solve this issue.

In the mean time, could you try adding a completion block to the animation, and within it add a call to `[self setNeedsLayout];`? I have a guess that it could help.

**Comment by danielamitay** [comment]
@jordanhbuiltbyhq I can confirm that this is resolved by using `CADisplayLink` instead, and the latest commit no longer has this issue.

**Comment by jordanhbuiltbyhq** [comment]
Awesome thanks for the quick resolution! Even though there's been 4 years of silence. ;) It's working nicely. I did notice if we use a `scrollPointsPerSecond` less than 15 it does stop auto scrolling.
